### ISSUE TITLE
Create a list of standards and write a first draft

### ISSUE THREAD

**Issue by kfriedman** [NYPL/engineering-general#10]
Based on our meeting on 7/28, we agreed to create a first draft of standards (and assigned owners) for the following:

- ^ Test coverage @emu47 
- ^ Logging @nodanaonlyzuul 
- Peer review @holingpoon 
- Git workflow - branch naming, PRs, release tagging @emu47 
- Deployment @jobinthomasnypl 
- Development environments @jobinthomasnypl 
- CI @jobinthomasnypl 
- ^ Documentation - README, functional, license, API/Swagger, talks to/listens to/dependencies, diagrams, workflows @gkallenberg @ktp242
- Accessibility 
- Performance @jbdalton 
- ^ Alerts/downtime @kfriedman
- Mission @emu47 
- Code of ethics
- Naming conventions - Lambdas, repos, errors, etc. - @rhernand3z 
- Ownership/responsibilities
- ^ Security - proper OAuth scopes, MFA enabled on AWS and other accounts @kfriedman @rhernand3z
- ^ Error handling @gkallenberg 
- Coding styles @nodanaonlyzuul 
- Code quality @gkallenberg @rhernand3z

^ indicates first priority as it's a blocker/critical for the ReCAP project

Next steps:

- Each assignee will create an issue for their standard in this repo
- Any developer interested in collaborating on the standard can comment on the issue
- The first draft of the standard will be created by end of the current sprint (8/9)
- Standards **SHOULD** follow the [RFC 2119](http://www.ietf.org/rfc/rfc2119.txt) language.

@EdwinGuzman, @nonword, @ktp242, and @rhernand3z: Since you weren't able to attend: 1. Do you have any standards you'd like to see created? 2. Would you like to volunteer for any of the unassigned standards above (or any other standard)?

Thanks everyone. Please let me know if I missed anything or if you have have any more thoughts. Y'all rock! 🎸 

cc: @jvarghese01, @ablwr

**Comment by kfriedman** [comment]
Yay! @rhernand3z agreed to tackle "Naming conventions - Lambdas, repos, errors, etc.".

**Comment by rhernand3z** [comment]
Please add me as part of:

Security (joining @kfriedman on this) 👍  and Code Quality (joining @gkallenberg on this)

**Comment by nodanaonlyzuul** [comment]
Doing a bit of spring cleaning in this repo's issues.
We used this ticket to kick start entries for this repo.
I think we can add or edit issues as need/want requires going forward.

Feel free to reopen this if I'm jumping to gun. No hard feelings.
🤗
