### ISSUE TITLE
Add CI section to testing standard?

### ISSUE THREAD

**Issue by kfriedman** [NYPL/engineering-general#27]
Perhaps we should a CI section to the testing standard?

Or, if we're not doing full CI, at least spell out our usage of a CI service like Travis?

**Comment by holingpoon** [comment]
@kfriedman Should this issue still be open? We have a page on [CI and Deployment](https://github.com/NYPL/engineering-general/blob/master/standards/ci-and-deployment.md)

**Comment by kfriedman** [comment]
Thanks @holingpoon! I'll close it.
