### ISSUE TITLE
AWS Profile names

### ISSUE THREAD

**Issue by holingpoon** [NYPL/engineering-general#31]
I noticed on some of our machines we used different names for our AWS profiles. As a recommendation, I'd like to suggest that the profile names be the Account ID or alias, e.g. `nypl-sandbox`, `nypl-digital-dev`, and `nypl` for AWS account run by Systems Engineering, when we log into AWS, so it is

1. Easier to remember and track on our local machines
2. When we write automation scripts, the profile names are unified and it's easier to share or install on our local machines.

Right now I'm only concerned about those three profiles, and engineers should be free to name other profiles to their preference.

**Comment by nodanaonlyzuul** [comment]
I agree with you that the AWS profile should match the alias.
Is nypl-box a real account!?

**Comment by holingpoon** [comment]
The mouse jumped and removed sand from sandbox. Wish that trick work when I'm at the beach. 😄

**Comment by rhernand3z** [comment]
I agree as well, keeping the profile names to account id or alias in lower snake-case delimited by `-` will make it consistent. Will send a PR for the Name Conventions section.

**Comment by holingpoon** [comment]
I'll close this issue once #36 is merged. Thanks @rhernand3z !

**Comment by holingpoon** [comment]
#36 is closed, therefore closing this issue.
