### ISSUE TITLE
Renaming ci-and-deployment.md to ci-coverage.md?

### ISSUE THREAD

**Issue by holingpoon** [NYPL/engineering-general#33]
@jobinthomasnypl I got a little confused thinking that the file `ci-and-deployment.md` covers both CI and Deployment. IMO Deployment may need another page. Is it possible to rename the file to `ci-coverage.md` or something else? Thanks!

**Comment by jobinthomasnypl** [comment]
We are doing deployment and ci together. I didn't get a chance to do
deployment yet. Focussing on getting recap to production now.

**Comment by jobinthomasnypl** [comment]
https://github.com/NYPL/engineering-general/issues/35

Issue for deployment created to add as part of CI. Closing this
