### ISSUE TITLE
Requesting addition to Documentation.md

### ISSUE THREAD

**Issue by holingpoon** [NYPL/engineering-general#34]
Is it okay to include this quote at the beginning of the [documentation standards page](https://github.com/NYPL/engineering-general/blob/master/standards/documentation.md)? It's been on my mind. 😄 

“Documentation is a love letter that you write to your future self.”
— Damian Conway

**Comment by rhernand3z** [comment]
I think that is a cool quote, 👍

**Comment by nodanaonlyzuul** [comment]
Hahah - yes - it's a cool quote - send me a PR and I'll accept!
