### ISSUE TITLE
Create onboarding documentation for new developers

### ISSUE THREAD

**Issue by kfriedman** [NYPL/engineering-general#45]
I think it might be a good idea to add an "Onboarding" document to this repo to help new developers get up to speed.

Do you know of any existing documents that we can build on for @gkallenberg @nodanaonlyzuul?

@thisisstephenbetts, what was helpful to you in the onboarding process?

Maybe we can use this issue to help create this document.

CC: @jvarghese01

**Comment by nodanaonlyzuul** [comment]
We have https://github.com/NYPL/onboarding-offboarding which is a checklist of services we use.

**Comment by thisisstephenbetts** [comment]
Yeah, I found it really helpful. I'll need to go back and check which bits worked and which didn't, but essentially it was really good and useful.

**Comment by kfriedman** [comment]
This is great. @nodanaonlyzuul would you mind if I moved this over to this repo?

Was there anything else that was helpful to you @thisisstephenbetts? Anything you _wish_ you had when you joined NYPL?

**Comment by thisisstephenbetts** [comment]
I spent a lot of time with your Welcome Links (https://docs.google.com/document/d/1bqfYHGujsAIAh0jhbToNSygrUiyeLLbfVIuiObaCcyI/edit). Basically I dived into anything with glossaries, overviews and diagrams. But it's context sensitive — the ReCAP stuff would be less important for anyone joining right now.

Something like that would be a good basis for expanding.

**Comment by nodanaonlyzuul** [comment]
@kfriedman - feel free to move NYPL/onboarding-offboarding here if you feel like its contents aren't sensitive. Or if it feels a bit private then you could link to it from this repo.

**Comment by kfriedman** [comment]
Cool. I might do that @nodanaonlyzuul.

**Comment by asyroyez** [comment]
I'm keeping an eye on this since I'd love to help in whatever capacity I am able in the near future.

**Comment by nodanaonlyzuul** [comment]
I'm doing a bit of housekeeping and this this was resolved in https://github.com/NYPL/engineering-general/pull/47.

@kfriedman, or anyone else really, feel free to reopen.
