### ISSUE TITLE
Graceful Slack Offboarding

### ISSUE THREAD

**Issue by holingpoon** [NYPL/engineering-general#50]
After a wonderful conversation with @winniequinn regarding offboarding staff on Slack, she suggested the following wonderful ideas:

- Convert the account as guest access to #general channel
- Keep the guest access for 3 months as part of the offboarding process.

That way, we can DM the guest while the account is still active for those three months. The guest access only to #general channel will not incur new charges to our nypl.slack.com account.

Let me know what you think, @kfriedman, @nodanaonlyzuul. Please ping anyone who you think should join this conversation!

**Comment by nodanaonlyzuul** [comment]
I'm fine with this.
We could add copy in our offboarding docs for Slack that says something like.

1.  Convert the user to a gues in the #general channel.
2.  Create a calendar event for 3 months in the future, with 5 attendees (to ensure someone sees it) to deactivate the user.

This is a good idea @holingpoon & @winniequinn .

**Comment by winniequinn** [comment]
@nodanaonlyzuul 

> Create a calendar event for 3 months in the future, with 5 attendees (to ensure someone sees it) to deactivate the user.

There's actually an option to do this automatically as part of the Slack administrative interface, thankfully! No need to remember to do anything three months later: It'll remove the guest for you.

**Comment by nodanaonlyzuul** [comment]
That's great - thank you for the peek into the rarefied air of Slack org ownership.
Look at this stuff, isn't it neat?!
