### ISSUE TITLE
Who should review the Pull Requests?

### ISSUE THREAD

**Issue by holingpoon** [NYPL/engineering-general#56]
I was having a conversation with @katesweeney on who needs to be reviewers of [nypl-core](https://github.com/NYPL/nypl-core), and learned that I should include @saverkamp as a reviewer for pull requests.

I'm thinking, rather than asking around every time who should be included as reviewers, a Markdown file telling me maintainers/point-of-contacts I should include within each code repository, would work wonders. I have learned recently that Github gives special meaning to CONTRIBUTING.md at code repository's root level, and it is also a standard practice used at companies such as [Pantheon](https://github.com/pantheon-systems/documentation/blob/master/CONTRIBUTING.md) and [CircleCI](https://github.com/circleci/circleci-docs/blob/master/CONTRIBUTING.md).

While we can figure out which parts of the standards we can and should adopt, some instructions on how to submit a Pull Request within a file such as CONTRIBUTING.md would give me pointers on the workflow of a repo.

cc: @thisisstephenbetts @kfriedman @nodanaonlyzuul @nonword

**Comment by nodanaonlyzuul** [comment]
Howdy - there's a lot to think about in this write-up (Thank you!).
Regarding PRs - is the question "Who should a PR be assigned to?" or "Who is the stakeholder?"

**Comment by thisisstephenbetts** [comment]
When I was doing PRs for nypl_core, it was really good to have Shawn review
them. For those cases, she was both a peer reviewer of the change in the
traditional sense, but also a stakeholder.

My opinion, is that for repos where it's not obvious who is qualified to
verify the check, I think it's really useful to have a CONTRIBUTING.md file
saying who should (and process to, if necessary) review PRs. I think it's
less important for other repos as it's normally clearer, and the team is
small enough. But, so long as clear & maintained, a CONTRIBUTING file
should never be a bad thing.

Stephen.

**Comment by holingpoon** [comment]
@nodanaonlyzuul That is an excellent question. I was initially thinking, "Who should a PR be assigned to?" You made an excellent point of there is a difference between a stakeholder and a reviewer, while I'm gearing towards "Who should a PR be assigned to?", I think knowing who the stakeholders are (online or offline) is equally important.

**Comment by LucasCioffi** [comment]
@holingpoon as a new member of the team, I agree this would be great.

Another option instead of committing the list of names to source control is a single Google Doc or Sheet that lists each repo and the reviewer & stakeholder names.  This way when a new person joins or leaves, it's easy to update in one place rather than across many repos.
